[versions]
serialization = "1.2.1"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }

napier = "io.github.aakira:napier:1.5.0"

activity-compose = "androidx.activity:activity-compose:1.3.0-rc01"

accompanist-insets = "com.google.accompanist:accompanist-insets:0.13.0"

bundlizer = "dev.ahmedmourad.bundlizer:bundlizer-core:0.6.0"
