name: Build project

on:
  push:
    branches:
      - master

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pushed commit
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Check API
        uses: gradle/gradle-build-action@v2
        with:
          arguments: apiCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
